runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains